// Aqua relay Worker — Phase 1 (auth + pairing).
//
// Routes (checked before static assets, per run_worker_first):
//   GET  /agent?role=pc|phone&device=<id>  -> WebSocket upgrade → RelayRoom DO
//   POST /pair  {code, device}             -> redeem a pair code → {ok, token}
// Everything else falls through to static assets (the SPA / test page).
//
// `Env` is generated by `wrangler types` into worker-configuration.d.ts.

export { RelayRoom } from "./relay_room";

function json(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { "content-type": "application/json" },
  });
}

// ── valorant-api asset mirror (Phase 6) ──────────────────────────────────────
// In production the SPA fetches the agent/map catalog from same-origin /api/* and
// art from /cdn/*, so the phone never hotlinks valorant-api directly (better
// caching, no third-party dependency at runtime, and it keeps working if CORS or
// the upstream wobbles). Both are edge-cached. The media host embedded in catalog
// JSON is rewritten to /cdn so images resolve through this same mirror.
const VAPI = "https://valorant-api.com/v1";
const VMEDIA = "https://media.valorant-api.com";
const MEDIA_REWRITE = "https://media.valorant-api.com";

async function proxyJSON(request: Request, path: string, search: string): Promise<Response> {
  const cache = (caches as any).default as Cache;
  const cacheKey = new Request(new URL(request.url).toString(), { method: "GET" });
  const hit = await cache.match(cacheKey);
  if (hit) return hit;

  const upstream = await fetch(`${VAPI}${path}${search}`, {
    cf: { cacheTtl: 3600, cacheEverything: true },
  } as RequestInit);
  if (!upstream.ok) return new Response("upstream error", { status: 502 });

  // Rewrite absolute media URLs to our same-origin /cdn mirror.
  const body = (await upstream.text()).split(MEDIA_REWRITE).join("/cdn");
  const res = new Response(body, {
    status: 200,
    headers: {
      "content-type": "application/json; charset=utf-8",
      "cache-control": "public, max-age=3600",
      "access-control-allow-origin": "*",
    },
  });
  await cache.put(cacheKey, res.clone());
  return res;
}

async function proxyMedia(request: Request, path: string): Promise<Response> {
  const cache = (caches as any).default as Cache;
  const cacheKey = new Request(new URL(request.url).toString(), { method: "GET" });
  const hit = await cache.match(cacheKey);
  if (hit) return hit;

  const upstream = await fetch(`${VMEDIA}${path}`, {
    cf: { cacheTtl: 86400, cacheEverything: true },
  } as RequestInit);
  if (!upstream.ok) return new Response("not found", { status: upstream.status });

  const res = new Response(upstream.body, upstream);
  // Art is content-addressed by version → cache hard.
  res.headers.set("cache-control", "public, max-age=604800, immutable");
  res.headers.set("access-control-allow-origin", "*");
  await cache.put(cacheKey, res.clone());
  return res;
}

export default {
  async fetch(request, env): Promise<Response> {
    const url = new URL(request.url);

    // Asset mirror (GET only; path is appended to a fixed upstream host, so this
    // is not an open proxy). Checked before the SPA fallback.
    if (request.method === "GET" && url.pathname.startsWith("/api/")) {
      return proxyJSON(request, url.pathname.slice(4), url.search);
    }
    if (request.method === "GET" && url.pathname.startsWith("/cdn/")) {
      return proxyMedia(request, url.pathname.slice(4));
    }

    if (url.pathname === "/agent") {
      if (request.headers.get("Upgrade") !== "websocket") {
        return new Response("expected websocket", { status: 426 });
      }
      const device = url.searchParams.get("device");
      if (!device) return new Response("missing device", { status: 400 });
      return env.RELAY_ROOM.getByName(device).fetch(request);
    }

    if (url.pathname === "/pair") {
      if (request.method !== "POST") return json({ ok: false, error: "method_not_allowed" }, 405);
      let body: any;
      try {
        body = await request.json();
      } catch {
        return json({ ok: false, error: "bad_json" }, 400);
      }
      const device = body?.device;
      if (typeof device !== "string" || !device) {
        return json({ ok: false, error: "missing_device" }, 400);
      }
      // Forward to the device's room with just the code; the SPA is same-origin
      // so no CORS handling is needed.
      const stub = env.RELAY_ROOM.getByName(device);
      return stub.fetch(
        new Request("https://do/pair", {
          method: "POST",
          headers: { "content-type": "application/json" },
          body: JSON.stringify({ code: body.code }),
        }),
      );
    }

    return env.ASSETS.fetch(request);
  },
} satisfies ExportedHandler<Env>;
